# Ejercicios Numpy II

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [14]:
import numpy as np
np.__version__

my_array = np.arange(10)

print(np.flip(my_array[1::2]))



[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [[8 7]] del array `my_array`

In [26]:
print(np.flip(my_array[-3:-1]))

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [[2 1 0]] de `my_array`

In [27]:
print(np.flip(my_array[0:3]))

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [42]:



matriz = np.arange(20).reshape(4,5)
matriz[::-1]


array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [54]:
 # primero dato de la fila, después dato de la columna

matriz[0:2, 1:3 ]

array([[1, 2],
       [6, 7]])

In [75]:
matriz = np.arange(20).reshape(4,5)
matriz[::-1]

array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [111]:
matriz[1:15:3]

array([[5, 6, 7, 8, 9]])

In [89]:
#print("2 primeras filas y 3 primeras columnas\n", array_multi[:2, :3])
#matriz[0::3, 1::2]
matriz[1:3:2]


array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [113]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

x_bools = x == "Loro"

print(x[x_bools])

['Loro' 'Loro']


In [115]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
validar_x = np.array([0, 1, 1, 0, 1, ])

x[validar_x == 0]

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [124]:
elementos = np.arange(20).reshape(4,5)
elementos

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del **ejercicio 4**
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [155]:

matriz = np.arange(1,21).reshape(4,5)
matriz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [[1,2,0,0,4,0]]. El output sería [[0, 1, 4]]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [205]:
matriz_14 = np.random.randint(0,100, size =(10, 10))
print(matriz_14)
print(np.min(matriz_14))
print(np.max(matriz_14))

[[13  0 75 50 55 55  6 45 71 85]
 [75 90 92 93 46 18 92 62 56 35]
 [76  4 75 93 17 69 22 43 85 57]
 [66 92 51 67 18 62 92 39  9 46]
 [12 15 97 65 18 63 31 41 21 77]
 [81  7 79 24 97 58 29 70 70 81]
 [12 65 18 45  7 73 38 93 40  7]
 [30 16 36 54 86 95 24 53 34 43]
 [69 81 44  9 72 63 91 21 38 67]
 [89 73 52 39 43 40 53  1 76 83]]
0
97


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [200]:
alea_vector = np.random.rand(30)
print(alea_vector)


[0.10671845 0.44650877 0.60935268 0.65391087 0.72798422 0.65756776
 0.17534655 0.75883159 0.23279833 0.70684587 0.77439458 0.49785913
 0.77516406 0.94631589 0.14630813 0.84754114 0.1599486  0.00444453
 0.45951818 0.24004191 0.64649379 0.06025077 0.6133372  0.8686025
 0.39103573 0.57981371 0.35163594 0.10409494 0.52900593 0.80052582]


In [201]:
media_vector = np.mean(alea_vector)
print(media_vector)

0.49573991902814357


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

## Ejercicio 17
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [181]:

a = np.array([[0, 1], [0, 1]])
np.tile(a, (4,4))



array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [175]:
aleatoria_matriz = np.random.randint(30, size = (5,5))
print(aleatoria_matriz)
media = np.mean(aleatoria_matriz)
desviación_estándar =np.std(aleatoria_matriz)
resta =aleatoria_matriz - media
dividir = resta / desviación_estándar
print(dividir)

[[ 1  4 14  8 24]
 [ 7 11 20 15  3]
 [ 4 26  4  3 29]
 [19  4  5 15 21]
 [ 8 11  5 16  2]]
[[-1.25466142 -0.88419053  0.35071245 -0.39022934  1.58561542]
 [-0.51371964 -0.01975845  1.09165423  0.47420274 -1.00768083]
 [-0.88419053  1.83259602 -0.88419053 -1.00768083  2.20306691]
 [ 0.96816393 -0.88419053 -0.76070023  0.47420274  1.21514453]
 [-0.39022934 -0.01975845 -0.76070023  0.59769304 -1.13117113]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [164]:
x = np.arange(11)
x2copy = x.copy()

x2copy[3:9] = -1
print(x2copy)
x2copy != -1


[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


array([ True,  True,  True, False, False, False, False, False, False,
        True,  True])

## Ejercicio 21 
#### Bonus track. Mini hundir la flota para ir practicando.
##### Te ayudará a entender la lógica de la tarea Hundir la Flota.
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.